// Code generated by protoc-gen-go. DO NOT EDIT.
// source: row.proto

package row

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Row struct {
	Column0              []byte   `protobuf:"bytes,1,opt,name=column0,proto3" json:"column0,omitempty"`
	Column1              []byte   `protobuf:"bytes,2,opt,name=column1,proto3" json:"column1,omitempty"`
	Column2              []byte   `protobuf:"bytes,3,opt,name=column2,proto3" json:"column2,omitempty"`
	Column3              []byte   `protobuf:"bytes,4,opt,name=column3,proto3" json:"column3,omitempty"`
	Column4              []byte   `protobuf:"bytes,5,opt,name=column4,proto3" json:"column4,omitempty"`
	Column5              []byte   `protobuf:"bytes,6,opt,name=column5,proto3" json:"column5,omitempty"`
	Column6              []byte   `protobuf:"bytes,7,opt,name=column6,proto3" json:"column6,omitempty"`
	Column7              []byte   `protobuf:"bytes,8,opt,name=column7,proto3" json:"column7,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfce2cce8f2e8cd, []int{0}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetColumn0() []byte {
	if m != nil {
		return m.Column0
	}
	return nil
}

func (m *Row) GetColumn1() []byte {
	if m != nil {
		return m.Column1
	}
	return nil
}

func (m *Row) GetColumn2() []byte {
	if m != nil {
		return m.Column2
	}
	return nil
}

func (m *Row) GetColumn3() []byte {
	if m != nil {
		return m.Column3
	}
	return nil
}

func (m *Row) GetColumn4() []byte {
	if m != nil {
		return m.Column4
	}
	return nil
}

func (m *Row) GetColumn5() []byte {
	if m != nil {
		return m.Column5
	}
	return nil
}

func (m *Row) GetColumn6() []byte {
	if m != nil {
		return m.Column6
	}
	return nil
}

func (m *Row) GetColumn7() []byte {
	if m != nil {
		return m.Column7
	}
	return nil
}

func init() {
	proto.RegisterType((*Row)(nil), "row.Row")
}

func init() { proto.RegisterFile("row.proto", fileDescriptor_dbfce2cce8f2e8cd) }

var fileDescriptor_dbfce2cce8f2e8cd = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0x3d, 0x0a, 0x82, 0x31,
	0x10, 0x06, 0x61, 0x62, 0x34, 0xd1, 0x60, 0x95, 0xea, 0x2d, 0xc5, 0xca, 0x4a, 0xcc, 0xff, 0x3d,
	0x72, 0x04, 0x6d, 0xd5, 0x95, 0xa0, 0xe4, 0xa4, 0xde, 0x47, 0x10, 0x3e, 0x76, 0xcb, 0xe1, 0xa9,
	0xc6, 0xed, 0x06, 0xcd, 0xf3, 0x6b, 0xd0, 0x9b, 0xbc, 0x1e, 0x34, 0x8f, 0x5f, 0xe5, 0x74, 0xa7,
	0xe9, 0xe1, 0xec, 0x8d, 0xee, 0x9f, 0xc7, 0xf3, 0x02, 0x75, 0x50, 0xa7, 0x7d, 0x5f, 0x92, 0x25,
	0x60, 0x25, 0x25, 0xb0, 0x44, 0x68, 0x29, 0x91, 0x25, 0x61, 0x2d, 0x25, 0xb1, 0x64, 0x6c, 0xa4,
	0x64, 0x96, 0x02, 0x23, 0xa5, 0xb0, 0x54, 0x58, 0x29, 0x95, 0xa5, 0x61, 0x2b, 0xa5, 0x5d, 0xcd,
	0xff, 0x31, 0xfd, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x7a, 0xff, 0x45, 0xf0, 0x00, 0x00, 0x00,
}
